CREATE TABLE IF NOT EXISTS gauge_metrics (
    name TEXT PRIMARY KEY,
    value DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS counter_metrics (
    name TEXT PRIMARY KEY,
    value BIGINT NOT NULL
);

